name: Node Apps CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  app1-test-and-build:
    name: App1 Test and Docker Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app1/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Docker Image
        run: docker build -t app1-image .

  app2-test-and-build:
    name: App2 Test and Docker Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app2/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Docker Image
        run: docker build -t app2-image .

  BuildApps:
    name: buildAppp
    uses: ./.github/workflows/run-build.yml
    with: 
      env: dev
      filePath: app1
      appDockerName: app1-image
